services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - ../../.env
    ports:
      - "27017:27017"  
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
